// Code generated by protoc-gen-go. DO NOT EDIT.
// source: meta.proto

package main

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type ValueType int32

const (
	ValueType_unknown   ValueType = 0
	ValueType_double    ValueType = 1
	ValueType_int64     ValueType = 2
	ValueType_string    ValueType = 3
	ValueType_timestamp ValueType = 4
	ValueType_boolean   ValueType = 5
	ValueType_bytes     ValueType = 6
	ValueType_key       ValueType = 7
	ValueType_uint64    ValueType = 8
)

var ValueType_name = map[int32]string{
	0: "unknown",
	1: "double",
	2: "int64",
	3: "string",
	4: "timestamp",
	5: "boolean",
	6: "bytes",
	7: "key",
	8: "uint64",
}

var ValueType_value = map[string]int32{
	"unknown":   0,
	"double":    1,
	"int64":     2,
	"string":    3,
	"timestamp": 4,
	"boolean":   5,
	"bytes":     6,
	"key":       7,
	"uint64":    8,
}

func (x ValueType) String() string {
	return proto.EnumName(ValueType_name, int32(x))
}

func (ValueType) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_3b5ea8fe65782bcc, []int{0}
}

type SchemaFieldEditorInfoType int32

const (
	SchemaFieldEditorInfoType_default  SchemaFieldEditorInfoType = 0
	SchemaFieldEditorInfoType_password SchemaFieldEditorInfoType = 1
	SchemaFieldEditorInfoType_lookup   SchemaFieldEditorInfoType = 2
)

var SchemaFieldEditorInfoType_name = map[int32]string{
	0: "default",
	1: "password",
	2: "lookup",
}

var SchemaFieldEditorInfoType_value = map[string]int32{
	"default":  0,
	"password": 1,
	"lookup":   2,
}

func (x SchemaFieldEditorInfoType) String() string {
	return proto.EnumName(SchemaFieldEditorInfoType_name, int32(x))
}

func (SchemaFieldEditorInfoType) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_3b5ea8fe65782bcc, []int{1}
}

type SchemaIndexType int32

const (
	SchemaIndexType_unspecified SchemaIndexType = 0
	SchemaIndexType_memory      SchemaIndexType = 1
)

var SchemaIndexType_name = map[int32]string{
	0: "unspecified",
	1: "memory",
}

var SchemaIndexType_value = map[string]int32{
	"unspecified": 0,
	"memory":      1,
}

func (x SchemaIndexType) String() string {
	return proto.EnumName(SchemaIndexType_name, int32(x))
}

func (SchemaIndexType) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_3b5ea8fe65782bcc, []int{2}
}

type PartitionId struct {
	Namespace            string   `protobuf:"bytes,1,opt,name=namespace,proto3" json:"namespace,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *PartitionId) Reset()         { *m = PartitionId{} }
func (m *PartitionId) String() string { return proto.CompactTextString(m) }
func (*PartitionId) ProtoMessage()    {}
func (*PartitionId) Descriptor() ([]byte, []int) {
	return fileDescriptor_3b5ea8fe65782bcc, []int{0}
}

func (m *PartitionId) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PartitionId.Unmarshal(m, b)
}
func (m *PartitionId) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PartitionId.Marshal(b, m, deterministic)
}
func (m *PartitionId) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PartitionId.Merge(m, src)
}
func (m *PartitionId) XXX_Size() int {
	return xxx_messageInfo_PartitionId.Size(m)
}
func (m *PartitionId) XXX_DiscardUnknown() {
	xxx_messageInfo_PartitionId.DiscardUnknown(m)
}

var xxx_messageInfo_PartitionId proto.InternalMessageInfo

func (m *PartitionId) GetNamespace() string {
	if m != nil {
		return m.Namespace
	}
	return ""
}

type PathElement struct {
	Kind string `protobuf:"bytes,1,opt,name=kind,proto3" json:"kind,omitempty"`
	// Types that are valid to be assigned to IdType:
	//	*PathElement_Id
	//	*PathElement_Name
	IdType               isPathElement_IdType `protobuf_oneof:"idType"`
	XXX_NoUnkeyedLiteral struct{}             `json:"-"`
	XXX_unrecognized     []byte               `json:"-"`
	XXX_sizecache        int32                `json:"-"`
}

func (m *PathElement) Reset()         { *m = PathElement{} }
func (m *PathElement) String() string { return proto.CompactTextString(m) }
func (*PathElement) ProtoMessage()    {}
func (*PathElement) Descriptor() ([]byte, []int) {
	return fileDescriptor_3b5ea8fe65782bcc, []int{1}
}

func (m *PathElement) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PathElement.Unmarshal(m, b)
}
func (m *PathElement) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PathElement.Marshal(b, m, deterministic)
}
func (m *PathElement) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PathElement.Merge(m, src)
}
func (m *PathElement) XXX_Size() int {
	return xxx_messageInfo_PathElement.Size(m)
}
func (m *PathElement) XXX_DiscardUnknown() {
	xxx_messageInfo_PathElement.DiscardUnknown(m)
}

var xxx_messageInfo_PathElement proto.InternalMessageInfo

func (m *PathElement) GetKind() string {
	if m != nil {
		return m.Kind
	}
	return ""
}

type isPathElement_IdType interface {
	isPathElement_IdType()
}

type PathElement_Id struct {
	Id int64 `protobuf:"varint,2,opt,name=id,proto3,oneof"`
}

type PathElement_Name struct {
	Name string `protobuf:"bytes,3,opt,name=name,proto3,oneof"`
}

func (*PathElement_Id) isPathElement_IdType() {}

func (*PathElement_Name) isPathElement_IdType() {}

func (m *PathElement) GetIdType() isPathElement_IdType {
	if m != nil {
		return m.IdType
	}
	return nil
}

func (m *PathElement) GetId() int64 {
	if x, ok := m.GetIdType().(*PathElement_Id); ok {
		return x.Id
	}
	return 0
}

func (m *PathElement) GetName() string {
	if x, ok := m.GetIdType().(*PathElement_Name); ok {
		return x.Name
	}
	return ""
}

// XXX_OneofWrappers is for the internal use of the proto package.
func (*PathElement) XXX_OneofWrappers() []interface{} {
	return []interface{}{
		(*PathElement_Id)(nil),
		(*PathElement_Name)(nil),
	}
}

type Key struct {
	PartitionId          *PartitionId   `protobuf:"bytes,1,opt,name=partitionId,proto3" json:"partitionId,omitempty"`
	Path                 []*PathElement `protobuf:"bytes,2,rep,name=path,proto3" json:"path,omitempty"`
	XXX_NoUnkeyedLiteral struct{}       `json:"-"`
	XXX_unrecognized     []byte         `json:"-"`
	XXX_sizecache        int32          `json:"-"`
}

func (m *Key) Reset()         { *m = Key{} }
func (m *Key) String() string { return proto.CompactTextString(m) }
func (*Key) ProtoMessage()    {}
func (*Key) Descriptor() ([]byte, []int) {
	return fileDescriptor_3b5ea8fe65782bcc, []int{2}
}

func (m *Key) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Key.Unmarshal(m, b)
}
func (m *Key) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Key.Marshal(b, m, deterministic)
}
func (m *Key) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Key.Merge(m, src)
}
func (m *Key) XXX_Size() int {
	return xxx_messageInfo_Key.Size(m)
}
func (m *Key) XXX_DiscardUnknown() {
	xxx_messageInfo_Key.DiscardUnknown(m)
}

var xxx_messageInfo_Key proto.InternalMessageInfo

func (m *Key) GetPartitionId() *PartitionId {
	if m != nil {
		return m.PartitionId
	}
	return nil
}

func (m *Key) GetPath() []*PathElement {
	if m != nil {
		return m.Path
	}
	return nil
}

type Value struct {
	Id                   int32     `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Type                 ValueType `protobuf:"varint,2,opt,name=type,proto3,enum=meta.ValueType" json:"type,omitempty"`
	DoubleValue          float64   `protobuf:"fixed64,3,opt,name=doubleValue,proto3" json:"doubleValue,omitempty"`
	Int64Value           int64     `protobuf:"varint,4,opt,name=int64Value,proto3" json:"int64Value,omitempty"`
	StringValue          string    `protobuf:"bytes,5,opt,name=stringValue,proto3" json:"stringValue,omitempty"`
	TimestampValue       []byte    `protobuf:"bytes,6,opt,name=timestampValue,proto3" json:"timestampValue,omitempty"`
	BooleanValue         bool      `protobuf:"varint,7,opt,name=booleanValue,proto3" json:"booleanValue,omitempty"`
	BytesValue           []byte    `protobuf:"bytes,8,opt,name=bytesValue,proto3" json:"bytesValue,omitempty"`
	KeyValue             *Key      `protobuf:"bytes,9,opt,name=keyValue,proto3" json:"keyValue,omitempty"`
	Uint64Value          uint64    `protobuf:"varint,10,opt,name=uint64Value,proto3" json:"uint64Value,omitempty"`
	XXX_NoUnkeyedLiteral struct{}  `json:"-"`
	XXX_unrecognized     []byte    `json:"-"`
	XXX_sizecache        int32     `json:"-"`
}

func (m *Value) Reset()         { *m = Value{} }
func (m *Value) String() string { return proto.CompactTextString(m) }
func (*Value) ProtoMessage()    {}
func (*Value) Descriptor() ([]byte, []int) {
	return fileDescriptor_3b5ea8fe65782bcc, []int{3}
}

func (m *Value) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Value.Unmarshal(m, b)
}
func (m *Value) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Value.Marshal(b, m, deterministic)
}
func (m *Value) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Value.Merge(m, src)
}
func (m *Value) XXX_Size() int {
	return xxx_messageInfo_Value.Size(m)
}
func (m *Value) XXX_DiscardUnknown() {
	xxx_messageInfo_Value.DiscardUnknown(m)
}

var xxx_messageInfo_Value proto.InternalMessageInfo

func (m *Value) GetId() int32 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *Value) GetType() ValueType {
	if m != nil {
		return m.Type
	}
	return ValueType_unknown
}

func (m *Value) GetDoubleValue() float64 {
	if m != nil {
		return m.DoubleValue
	}
	return 0
}

func (m *Value) GetInt64Value() int64 {
	if m != nil {
		return m.Int64Value
	}
	return 0
}

func (m *Value) GetStringValue() string {
	if m != nil {
		return m.StringValue
	}
	return ""
}

func (m *Value) GetTimestampValue() []byte {
	if m != nil {
		return m.TimestampValue
	}
	return nil
}

func (m *Value) GetBooleanValue() bool {
	if m != nil {
		return m.BooleanValue
	}
	return false
}

func (m *Value) GetBytesValue() []byte {
	if m != nil {
		return m.BytesValue
	}
	return nil
}

func (m *Value) GetKeyValue() *Key {
	if m != nil {
		return m.KeyValue
	}
	return nil
}

func (m *Value) GetUint64Value() uint64 {
	if m != nil {
		return m.Uint64Value
	}
	return 0
}

type SchemaField struct {
	Id                   int32                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Name                 string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Type                 ValueType              `protobuf:"varint,3,opt,name=type,proto3,enum=meta.ValueType" json:"type,omitempty"`
	Comment              string                 `protobuf:"bytes,4,opt,name=comment,proto3" json:"comment,omitempty"`
	Editor               *SchemaFieldEditorInfo `protobuf:"bytes,5,opt,name=editor,proto3" json:"editor,omitempty"`
	Readonly             bool                   `protobuf:"varint,6,opt,name=readonly,proto3" json:"readonly,omitempty"`
	XXX_NoUnkeyedLiteral struct{}               `json:"-"`
	XXX_unrecognized     []byte                 `json:"-"`
	XXX_sizecache        int32                  `json:"-"`
}

func (m *SchemaField) Reset()         { *m = SchemaField{} }
func (m *SchemaField) String() string { return proto.CompactTextString(m) }
func (*SchemaField) ProtoMessage()    {}
func (*SchemaField) Descriptor() ([]byte, []int) {
	return fileDescriptor_3b5ea8fe65782bcc, []int{4}
}

func (m *SchemaField) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SchemaField.Unmarshal(m, b)
}
func (m *SchemaField) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SchemaField.Marshal(b, m, deterministic)
}
func (m *SchemaField) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SchemaField.Merge(m, src)
}
func (m *SchemaField) XXX_Size() int {
	return xxx_messageInfo_SchemaField.Size(m)
}
func (m *SchemaField) XXX_DiscardUnknown() {
	xxx_messageInfo_SchemaField.DiscardUnknown(m)
}

var xxx_messageInfo_SchemaField proto.InternalMessageInfo

func (m *SchemaField) GetId() int32 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *SchemaField) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *SchemaField) GetType() ValueType {
	if m != nil {
		return m.Type
	}
	return ValueType_unknown
}

func (m *SchemaField) GetComment() string {
	if m != nil {
		return m.Comment
	}
	return ""
}

func (m *SchemaField) GetEditor() *SchemaFieldEditorInfo {
	if m != nil {
		return m.Editor
	}
	return nil
}

func (m *SchemaField) GetReadonly() bool {
	if m != nil {
		return m.Readonly
	}
	return false
}

type SchemaFieldEditorInfo struct {
	DisplayName          string                    `protobuf:"bytes,1,opt,name=displayName,proto3" json:"displayName,omitempty"`
	Type                 SchemaFieldEditorInfoType `protobuf:"varint,2,opt,name=type,proto3,enum=meta.SchemaFieldEditorInfoType" json:"type,omitempty"`
	EditorReadonly       bool                      `protobuf:"varint,3,opt,name=editorReadonly,proto3" json:"editorReadonly,omitempty"`
	ForeignType          string                    `protobuf:"bytes,4,opt,name=foreignType,proto3" json:"foreignType,omitempty"`
	XXX_NoUnkeyedLiteral struct{}                  `json:"-"`
	XXX_unrecognized     []byte                    `json:"-"`
	XXX_sizecache        int32                     `json:"-"`
}

func (m *SchemaFieldEditorInfo) Reset()         { *m = SchemaFieldEditorInfo{} }
func (m *SchemaFieldEditorInfo) String() string { return proto.CompactTextString(m) }
func (*SchemaFieldEditorInfo) ProtoMessage()    {}
func (*SchemaFieldEditorInfo) Descriptor() ([]byte, []int) {
	return fileDescriptor_3b5ea8fe65782bcc, []int{5}
}

func (m *SchemaFieldEditorInfo) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SchemaFieldEditorInfo.Unmarshal(m, b)
}
func (m *SchemaFieldEditorInfo) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SchemaFieldEditorInfo.Marshal(b, m, deterministic)
}
func (m *SchemaFieldEditorInfo) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SchemaFieldEditorInfo.Merge(m, src)
}
func (m *SchemaFieldEditorInfo) XXX_Size() int {
	return xxx_messageInfo_SchemaFieldEditorInfo.Size(m)
}
func (m *SchemaFieldEditorInfo) XXX_DiscardUnknown() {
	xxx_messageInfo_SchemaFieldEditorInfo.DiscardUnknown(m)
}

var xxx_messageInfo_SchemaFieldEditorInfo proto.InternalMessageInfo

func (m *SchemaFieldEditorInfo) GetDisplayName() string {
	if m != nil {
		return m.DisplayName
	}
	return ""
}

func (m *SchemaFieldEditorInfo) GetType() SchemaFieldEditorInfoType {
	if m != nil {
		return m.Type
	}
	return SchemaFieldEditorInfoType_default
}

func (m *SchemaFieldEditorInfo) GetEditorReadonly() bool {
	if m != nil {
		return m.EditorReadonly
	}
	return false
}

func (m *SchemaFieldEditorInfo) GetForeignType() string {
	if m != nil {
		return m.ForeignType
	}
	return ""
}

type SchemaKindEditor struct {
	Singular             string   `protobuf:"bytes,1,opt,name=singular,proto3" json:"singular,omitempty"`
	Plural               string   `protobuf:"bytes,2,opt,name=plural,proto3" json:"plural,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SchemaKindEditor) Reset()         { *m = SchemaKindEditor{} }
func (m *SchemaKindEditor) String() string { return proto.CompactTextString(m) }
func (*SchemaKindEditor) ProtoMessage()    {}
func (*SchemaKindEditor) Descriptor() ([]byte, []int) {
	return fileDescriptor_3b5ea8fe65782bcc, []int{6}
}

func (m *SchemaKindEditor) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SchemaKindEditor.Unmarshal(m, b)
}
func (m *SchemaKindEditor) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SchemaKindEditor.Marshal(b, m, deterministic)
}
func (m *SchemaKindEditor) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SchemaKindEditor.Merge(m, src)
}
func (m *SchemaKindEditor) XXX_Size() int {
	return xxx_messageInfo_SchemaKindEditor.Size(m)
}
func (m *SchemaKindEditor) XXX_DiscardUnknown() {
	xxx_messageInfo_SchemaKindEditor.DiscardUnknown(m)
}

var xxx_messageInfo_SchemaKindEditor proto.InternalMessageInfo

func (m *SchemaKindEditor) GetSingular() string {
	if m != nil {
		return m.Singular
	}
	return ""
}

func (m *SchemaKindEditor) GetPlural() string {
	if m != nil {
		return m.Plural
	}
	return ""
}

type SchemaKind struct {
	Fields               []*SchemaField    `protobuf:"bytes,2,rep,name=fields,proto3" json:"fields,omitempty"`
	Editor               *SchemaKindEditor `protobuf:"bytes,3,opt,name=editor,proto3" json:"editor,omitempty"`
	Indexes              []*SchemaIndex    `protobuf:"bytes,4,rep,name=indexes,proto3" json:"indexes,omitempty"`
	Ancestors            []string          `protobuf:"bytes,5,rep,name=ancestors,proto3" json:"ancestors,omitempty"`
	XXX_NoUnkeyedLiteral struct{}          `json:"-"`
	XXX_unrecognized     []byte            `json:"-"`
	XXX_sizecache        int32             `json:"-"`
}

func (m *SchemaKind) Reset()         { *m = SchemaKind{} }
func (m *SchemaKind) String() string { return proto.CompactTextString(m) }
func (*SchemaKind) ProtoMessage()    {}
func (*SchemaKind) Descriptor() ([]byte, []int) {
	return fileDescriptor_3b5ea8fe65782bcc, []int{7}
}

func (m *SchemaKind) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SchemaKind.Unmarshal(m, b)
}
func (m *SchemaKind) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SchemaKind.Marshal(b, m, deterministic)
}
func (m *SchemaKind) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SchemaKind.Merge(m, src)
}
func (m *SchemaKind) XXX_Size() int {
	return xxx_messageInfo_SchemaKind.Size(m)
}
func (m *SchemaKind) XXX_DiscardUnknown() {
	xxx_messageInfo_SchemaKind.DiscardUnknown(m)
}

var xxx_messageInfo_SchemaKind proto.InternalMessageInfo

func (m *SchemaKind) GetFields() []*SchemaField {
	if m != nil {
		return m.Fields
	}
	return nil
}

func (m *SchemaKind) GetEditor() *SchemaKindEditor {
	if m != nil {
		return m.Editor
	}
	return nil
}

func (m *SchemaKind) GetIndexes() []*SchemaIndex {
	if m != nil {
		return m.Indexes
	}
	return nil
}

func (m *SchemaKind) GetAncestors() []string {
	if m != nil {
		return m.Ancestors
	}
	return nil
}

type SchemaIndex struct {
	Name string          `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Type SchemaIndexType `protobuf:"varint,2,opt,name=type,proto3,enum=meta.SchemaIndexType" json:"type,omitempty"`
	// Types that are valid to be assigned to Value:
	//	*SchemaIndex_Computed
	//	*SchemaIndex_Field
	Value                isSchemaIndex_Value `protobuf_oneof:"value"`
	XXX_NoUnkeyedLiteral struct{}            `json:"-"`
	XXX_unrecognized     []byte              `json:"-"`
	XXX_sizecache        int32               `json:"-"`
}

func (m *SchemaIndex) Reset()         { *m = SchemaIndex{} }
func (m *SchemaIndex) String() string { return proto.CompactTextString(m) }
func (*SchemaIndex) ProtoMessage()    {}
func (*SchemaIndex) Descriptor() ([]byte, []int) {
	return fileDescriptor_3b5ea8fe65782bcc, []int{8}
}

func (m *SchemaIndex) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SchemaIndex.Unmarshal(m, b)
}
func (m *SchemaIndex) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SchemaIndex.Marshal(b, m, deterministic)
}
func (m *SchemaIndex) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SchemaIndex.Merge(m, src)
}
func (m *SchemaIndex) XXX_Size() int {
	return xxx_messageInfo_SchemaIndex.Size(m)
}
func (m *SchemaIndex) XXX_DiscardUnknown() {
	xxx_messageInfo_SchemaIndex.DiscardUnknown(m)
}

var xxx_messageInfo_SchemaIndex proto.InternalMessageInfo

func (m *SchemaIndex) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *SchemaIndex) GetType() SchemaIndexType {
	if m != nil {
		return m.Type
	}
	return SchemaIndexType_unspecified
}

type isSchemaIndex_Value interface {
	isSchemaIndex_Value()
}

type SchemaIndex_Computed struct {
	Computed *SchemaComputedIndex `protobuf:"bytes,3,opt,name=computed,proto3,oneof"`
}

type SchemaIndex_Field struct {
	Field string `protobuf:"bytes,4,opt,name=field,proto3,oneof"`
}

func (*SchemaIndex_Computed) isSchemaIndex_Value() {}

func (*SchemaIndex_Field) isSchemaIndex_Value() {}

func (m *SchemaIndex) GetValue() isSchemaIndex_Value {
	if m != nil {
		return m.Value
	}
	return nil
}

func (m *SchemaIndex) GetComputed() *SchemaComputedIndex {
	if x, ok := m.GetValue().(*SchemaIndex_Computed); ok {
		return x.Computed
	}
	return nil
}

func (m *SchemaIndex) GetField() string {
	if x, ok := m.GetValue().(*SchemaIndex_Field); ok {
		return x.Field
	}
	return ""
}

// XXX_OneofWrappers is for the internal use of the proto package.
func (*SchemaIndex) XXX_OneofWrappers() []interface{} {
	return []interface{}{
		(*SchemaIndex_Computed)(nil),
		(*SchemaIndex_Field)(nil),
	}
}

type SchemaComputedIndex struct {
	// Types that are valid to be assigned to Algorithm:
	//	*SchemaComputedIndex_Fnv64A
	//	*SchemaComputedIndex_Fnv64APair
	Algorithm            isSchemaComputedIndex_Algorithm `protobuf_oneof:"algorithm"`
	XXX_NoUnkeyedLiteral struct{}                        `json:"-"`
	XXX_unrecognized     []byte                          `json:"-"`
	XXX_sizecache        int32                           `json:"-"`
}

func (m *SchemaComputedIndex) Reset()         { *m = SchemaComputedIndex{} }
func (m *SchemaComputedIndex) String() string { return proto.CompactTextString(m) }
func (*SchemaComputedIndex) ProtoMessage()    {}
func (*SchemaComputedIndex) Descriptor() ([]byte, []int) {
	return fileDescriptor_3b5ea8fe65782bcc, []int{9}
}

func (m *SchemaComputedIndex) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SchemaComputedIndex.Unmarshal(m, b)
}
func (m *SchemaComputedIndex) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SchemaComputedIndex.Marshal(b, m, deterministic)
}
func (m *SchemaComputedIndex) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SchemaComputedIndex.Merge(m, src)
}
func (m *SchemaComputedIndex) XXX_Size() int {
	return xxx_messageInfo_SchemaComputedIndex.Size(m)
}
func (m *SchemaComputedIndex) XXX_DiscardUnknown() {
	xxx_messageInfo_SchemaComputedIndex.DiscardUnknown(m)
}

var xxx_messageInfo_SchemaComputedIndex proto.InternalMessageInfo

type isSchemaComputedIndex_Algorithm interface {
	isSchemaComputedIndex_Algorithm()
}

type SchemaComputedIndex_Fnv64A struct {
	Fnv64A *SchemaComputedIndexFnv64A `protobuf:"bytes,1,opt,name=fnv64a,proto3,oneof"`
}

type SchemaComputedIndex_Fnv64APair struct {
	Fnv64APair *SchemaComputedIndexFnv64APair `protobuf:"bytes,2,opt,name=fnv64a_pair,json=fnv64aPair,proto3,oneof"`
}

func (*SchemaComputedIndex_Fnv64A) isSchemaComputedIndex_Algorithm() {}

func (*SchemaComputedIndex_Fnv64APair) isSchemaComputedIndex_Algorithm() {}

func (m *SchemaComputedIndex) GetAlgorithm() isSchemaComputedIndex_Algorithm {
	if m != nil {
		return m.Algorithm
	}
	return nil
}

func (m *SchemaComputedIndex) GetFnv64A() *SchemaComputedIndexFnv64A {
	if x, ok := m.GetAlgorithm().(*SchemaComputedIndex_Fnv64A); ok {
		return x.Fnv64A
	}
	return nil
}

func (m *SchemaComputedIndex) GetFnv64APair() *SchemaComputedIndexFnv64APair {
	if x, ok := m.GetAlgorithm().(*SchemaComputedIndex_Fnv64APair); ok {
		return x.Fnv64APair
	}
	return nil
}

// XXX_OneofWrappers is for the internal use of the proto package.
func (*SchemaComputedIndex) XXX_OneofWrappers() []interface{} {
	return []interface{}{
		(*SchemaComputedIndex_Fnv64A)(nil),
		(*SchemaComputedIndex_Fnv64APair)(nil),
	}
}

type SchemaComputedIndexFnv64A struct {
	Field                string   `protobuf:"bytes,1,opt,name=field,proto3" json:"field,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SchemaComputedIndexFnv64A) Reset()         { *m = SchemaComputedIndexFnv64A{} }
func (m *SchemaComputedIndexFnv64A) String() string { return proto.CompactTextString(m) }
func (*SchemaComputedIndexFnv64A) ProtoMessage()    {}
func (*SchemaComputedIndexFnv64A) Descriptor() ([]byte, []int) {
	return fileDescriptor_3b5ea8fe65782bcc, []int{10}
}

func (m *SchemaComputedIndexFnv64A) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SchemaComputedIndexFnv64A.Unmarshal(m, b)
}
func (m *SchemaComputedIndexFnv64A) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SchemaComputedIndexFnv64A.Marshal(b, m, deterministic)
}
func (m *SchemaComputedIndexFnv64A) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SchemaComputedIndexFnv64A.Merge(m, src)
}
func (m *SchemaComputedIndexFnv64A) XXX_Size() int {
	return xxx_messageInfo_SchemaComputedIndexFnv64A.Size(m)
}
func (m *SchemaComputedIndexFnv64A) XXX_DiscardUnknown() {
	xxx_messageInfo_SchemaComputedIndexFnv64A.DiscardUnknown(m)
}

var xxx_messageInfo_SchemaComputedIndexFnv64A proto.InternalMessageInfo

func (m *SchemaComputedIndexFnv64A) GetField() string {
	if m != nil {
		return m.Field
	}
	return ""
}

type SchemaComputedIndexFnv64APair struct {
	Field1               string   `protobuf:"bytes,1,opt,name=field1,proto3" json:"field1,omitempty"`
	Field2               string   `protobuf:"bytes,2,opt,name=field2,proto3" json:"field2,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SchemaComputedIndexFnv64APair) Reset()         { *m = SchemaComputedIndexFnv64APair{} }
func (m *SchemaComputedIndexFnv64APair) String() string { return proto.CompactTextString(m) }
func (*SchemaComputedIndexFnv64APair) ProtoMessage()    {}
func (*SchemaComputedIndexFnv64APair) Descriptor() ([]byte, []int) {
	return fileDescriptor_3b5ea8fe65782bcc, []int{11}
}

func (m *SchemaComputedIndexFnv64APair) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SchemaComputedIndexFnv64APair.Unmarshal(m, b)
}
func (m *SchemaComputedIndexFnv64APair) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SchemaComputedIndexFnv64APair.Marshal(b, m, deterministic)
}
func (m *SchemaComputedIndexFnv64APair) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SchemaComputedIndexFnv64APair.Merge(m, src)
}
func (m *SchemaComputedIndexFnv64APair) XXX_Size() int {
	return xxx_messageInfo_SchemaComputedIndexFnv64APair.Size(m)
}
func (m *SchemaComputedIndexFnv64APair) XXX_DiscardUnknown() {
	xxx_messageInfo_SchemaComputedIndexFnv64APair.DiscardUnknown(m)
}

var xxx_messageInfo_SchemaComputedIndexFnv64APair proto.InternalMessageInfo

func (m *SchemaComputedIndexFnv64APair) GetField1() string {
	if m != nil {
		return m.Field1
	}
	return ""
}

func (m *SchemaComputedIndexFnv64APair) GetField2() string {
	if m != nil {
		return m.Field2
	}
	return ""
}

type Schema struct {
	Name                 string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Kinds                map[string]*SchemaKind `protobuf:"bytes,2,rep,name=kinds,proto3" json:"kinds,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"`
	XXX_NoUnkeyedLiteral struct{}               `json:"-"`
	XXX_unrecognized     []byte                 `json:"-"`
	XXX_sizecache        int32                  `json:"-"`
}

func (m *Schema) Reset()         { *m = Schema{} }
func (m *Schema) String() string { return proto.CompactTextString(m) }
func (*Schema) ProtoMessage()    {}
func (*Schema) Descriptor() ([]byte, []int) {
	return fileDescriptor_3b5ea8fe65782bcc, []int{12}
}

func (m *Schema) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Schema.Unmarshal(m, b)
}
func (m *Schema) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Schema.Marshal(b, m, deterministic)
}
func (m *Schema) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Schema.Merge(m, src)
}
func (m *Schema) XXX_Size() int {
	return xxx_messageInfo_Schema.Size(m)
}
func (m *Schema) XXX_DiscardUnknown() {
	xxx_messageInfo_Schema.DiscardUnknown(m)
}

var xxx_messageInfo_Schema proto.InternalMessageInfo

func (m *Schema) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *Schema) GetKinds() map[string]*SchemaKind {
	if m != nil {
		return m.Kinds
	}
	return nil
}

type GetSchemaRequest struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetSchemaRequest) Reset()         { *m = GetSchemaRequest{} }
func (m *GetSchemaRequest) String() string { return proto.CompactTextString(m) }
func (*GetSchemaRequest) ProtoMessage()    {}
func (*GetSchemaRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_3b5ea8fe65782bcc, []int{13}
}

func (m *GetSchemaRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetSchemaRequest.Unmarshal(m, b)
}
func (m *GetSchemaRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetSchemaRequest.Marshal(b, m, deterministic)
}
func (m *GetSchemaRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetSchemaRequest.Merge(m, src)
}
func (m *GetSchemaRequest) XXX_Size() int {
	return xxx_messageInfo_GetSchemaRequest.Size(m)
}
func (m *GetSchemaRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GetSchemaRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GetSchemaRequest proto.InternalMessageInfo

type GetSchemaResponse struct {
	Schema               *Schema  `protobuf:"bytes,1,opt,name=schema,proto3" json:"schema,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetSchemaResponse) Reset()         { *m = GetSchemaResponse{} }
func (m *GetSchemaResponse) String() string { return proto.CompactTextString(m) }
func (*GetSchemaResponse) ProtoMessage()    {}
func (*GetSchemaResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_3b5ea8fe65782bcc, []int{14}
}

func (m *GetSchemaResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetSchemaResponse.Unmarshal(m, b)
}
func (m *GetSchemaResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetSchemaResponse.Marshal(b, m, deterministic)
}
func (m *GetSchemaResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetSchemaResponse.Merge(m, src)
}
func (m *GetSchemaResponse) XXX_Size() int {
	return xxx_messageInfo_GetSchemaResponse.Size(m)
}
func (m *GetSchemaResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_GetSchemaResponse.DiscardUnknown(m)
}

var xxx_messageInfo_GetSchemaResponse proto.InternalMessageInfo

func (m *GetSchemaResponse) GetSchema() *Schema {
	if m != nil {
		return m.Schema
	}
	return nil
}

type MetaListEntitiesRequest struct {
	Start                []byte   `protobuf:"bytes,1,opt,name=start,proto3" json:"start,omitempty"`
	Limit                uint32   `protobuf:"varint,2,opt,name=limit,proto3" json:"limit,omitempty"`
	KindName             string   `protobuf:"bytes,3,opt,name=kindName,proto3" json:"kindName,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *MetaListEntitiesRequest) Reset()         { *m = MetaListEntitiesRequest{} }
func (m *MetaListEntitiesRequest) String() string { return proto.CompactTextString(m) }
func (*MetaListEntitiesRequest) ProtoMessage()    {}
func (*MetaListEntitiesRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_3b5ea8fe65782bcc, []int{15}
}

func (m *MetaListEntitiesRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_MetaListEntitiesRequest.Unmarshal(m, b)
}
func (m *MetaListEntitiesRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_MetaListEntitiesRequest.Marshal(b, m, deterministic)
}
func (m *MetaListEntitiesRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MetaListEntitiesRequest.Merge(m, src)
}
func (m *MetaListEntitiesRequest) XXX_Size() int {
	return xxx_messageInfo_MetaListEntitiesRequest.Size(m)
}
func (m *MetaListEntitiesRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_MetaListEntitiesRequest.DiscardUnknown(m)
}

var xxx_messageInfo_MetaListEntitiesRequest proto.InternalMessageInfo

func (m *MetaListEntitiesRequest) GetStart() []byte {
	if m != nil {
		return m.Start
	}
	return nil
}

func (m *MetaListEntitiesRequest) GetLimit() uint32 {
	if m != nil {
		return m.Limit
	}
	return 0
}

func (m *MetaListEntitiesRequest) GetKindName() string {
	if m != nil {
		return m.KindName
	}
	return ""
}

type MetaListEntitiesResponse struct {
	Next                 []byte        `protobuf:"bytes,1,opt,name=next,proto3" json:"next,omitempty"`
	MoreResults          bool          `protobuf:"varint,2,opt,name=moreResults,proto3" json:"moreResults,omitempty"`
	Entities             []*MetaEntity `protobuf:"bytes,3,rep,name=entities,proto3" json:"entities,omitempty"`
	XXX_NoUnkeyedLiteral struct{}      `json:"-"`
	XXX_unrecognized     []byte        `json:"-"`
	XXX_sizecache        int32         `json:"-"`
}

func (m *MetaListEntitiesResponse) Reset()         { *m = MetaListEntitiesResponse{} }
func (m *MetaListEntitiesResponse) String() string { return proto.CompactTextString(m) }
func (*MetaListEntitiesResponse) ProtoMessage()    {}
func (*MetaListEntitiesResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_3b5ea8fe65782bcc, []int{16}
}

func (m *MetaListEntitiesResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_MetaListEntitiesResponse.Unmarshal(m, b)
}
func (m *MetaListEntitiesResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_MetaListEntitiesResponse.Marshal(b, m, deterministic)
}
func (m *MetaListEntitiesResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MetaListEntitiesResponse.Merge(m, src)
}
func (m *MetaListEntitiesResponse) XXX_Size() int {
	return xxx_messageInfo_MetaListEntitiesResponse.Size(m)
}
func (m *MetaListEntitiesResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_MetaListEntitiesResponse.DiscardUnknown(m)
}

var xxx_messageInfo_MetaListEntitiesResponse proto.InternalMessageInfo

func (m *MetaListEntitiesResponse) GetNext() []byte {
	if m != nil {
		return m.Next
	}
	return nil
}

func (m *MetaListEntitiesResponse) GetMoreResults() bool {
	if m != nil {
		return m.MoreResults
	}
	return false
}

func (m *MetaListEntitiesResponse) GetEntities() []*MetaEntity {
	if m != nil {
		return m.Entities
	}
	return nil
}

type MetaEntity struct {
	Key                  *Key     `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`
	Values               []*Value `protobuf:"bytes,2,rep,name=values,proto3" json:"values,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *MetaEntity) Reset()         { *m = MetaEntity{} }
func (m *MetaEntity) String() string { return proto.CompactTextString(m) }
func (*MetaEntity) ProtoMessage()    {}
func (*MetaEntity) Descriptor() ([]byte, []int) {
	return fileDescriptor_3b5ea8fe65782bcc, []int{17}
}

func (m *MetaEntity) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_MetaEntity.Unmarshal(m, b)
}
func (m *MetaEntity) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_MetaEntity.Marshal(b, m, deterministic)
}
func (m *MetaEntity) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MetaEntity.Merge(m, src)
}
func (m *MetaEntity) XXX_Size() int {
	return xxx_messageInfo_MetaEntity.Size(m)
}
func (m *MetaEntity) XXX_DiscardUnknown() {
	xxx_messageInfo_MetaEntity.DiscardUnknown(m)
}

var xxx_messageInfo_MetaEntity proto.InternalMessageInfo

func (m *MetaEntity) GetKey() *Key {
	if m != nil {
		return m.Key
	}
	return nil
}

func (m *MetaEntity) GetValues() []*Value {
	if m != nil {
		return m.Values
	}
	return nil
}

type GetDefaultPartitionIdRequest struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetDefaultPartitionIdRequest) Reset()         { *m = GetDefaultPartitionIdRequest{} }
func (m *GetDefaultPartitionIdRequest) String() string { return proto.CompactTextString(m) }
func (*GetDefaultPartitionIdRequest) ProtoMessage()    {}
func (*GetDefaultPartitionIdRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_3b5ea8fe65782bcc, []int{18}
}

func (m *GetDefaultPartitionIdRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetDefaultPartitionIdRequest.Unmarshal(m, b)
}
func (m *GetDefaultPartitionIdRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetDefaultPartitionIdRequest.Marshal(b, m, deterministic)
}
func (m *GetDefaultPartitionIdRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetDefaultPartitionIdRequest.Merge(m, src)
}
func (m *GetDefaultPartitionIdRequest) XXX_Size() int {
	return xxx_messageInfo_GetDefaultPartitionIdRequest.Size(m)
}
func (m *GetDefaultPartitionIdRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GetDefaultPartitionIdRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GetDefaultPartitionIdRequest proto.InternalMessageInfo

type GetDefaultPartitionIdResponse struct {
	Namespace            string   `protobuf:"bytes,1,opt,name=namespace,proto3" json:"namespace,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetDefaultPartitionIdResponse) Reset()         { *m = GetDefaultPartitionIdResponse{} }
func (m *GetDefaultPartitionIdResponse) String() string { return proto.CompactTextString(m) }
func (*GetDefaultPartitionIdResponse) ProtoMessage()    {}
func (*GetDefaultPartitionIdResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_3b5ea8fe65782bcc, []int{19}
}

func (m *GetDefaultPartitionIdResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetDefaultPartitionIdResponse.Unmarshal(m, b)
}
func (m *GetDefaultPartitionIdResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetDefaultPartitionIdResponse.Marshal(b, m, deterministic)
}
func (m *GetDefaultPartitionIdResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetDefaultPartitionIdResponse.Merge(m, src)
}
func (m *GetDefaultPartitionIdResponse) XXX_Size() int {
	return xxx_messageInfo_GetDefaultPartitionIdResponse.Size(m)
}
func (m *GetDefaultPartitionIdResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_GetDefaultPartitionIdResponse.DiscardUnknown(m)
}

var xxx_messageInfo_GetDefaultPartitionIdResponse proto.InternalMessageInfo

func (m *GetDefaultPartitionIdResponse) GetNamespace() string {
	if m != nil {
		return m.Namespace
	}
	return ""
}

type MetaGetEntityRequest struct {
	Key                  *Key     `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`
	KindName             string   `protobuf:"bytes,2,opt,name=kindName,proto3" json:"kindName,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *MetaGetEntityRequest) Reset()         { *m = MetaGetEntityRequest{} }
func (m *MetaGetEntityRequest) String() string { return proto.CompactTextString(m) }
func (*MetaGetEntityRequest) ProtoMessage()    {}
func (*MetaGetEntityRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_3b5ea8fe65782bcc, []int{20}
}

func (m *MetaGetEntityRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_MetaGetEntityRequest.Unmarshal(m, b)
}
func (m *MetaGetEntityRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_MetaGetEntityRequest.Marshal(b, m, deterministic)
}
func (m *MetaGetEntityRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MetaGetEntityRequest.Merge(m, src)
}
func (m *MetaGetEntityRequest) XXX_Size() int {
	return xxx_messageInfo_MetaGetEntityRequest.Size(m)
}
func (m *MetaGetEntityRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_MetaGetEntityRequest.DiscardUnknown(m)
}

var xxx_messageInfo_MetaGetEntityRequest proto.InternalMessageInfo

func (m *MetaGetEntityRequest) GetKey() *Key {
	if m != nil {
		return m.Key
	}
	return nil
}

func (m *MetaGetEntityRequest) GetKindName() string {
	if m != nil {
		return m.KindName
	}
	return ""
}

type MetaGetEntityResponse struct {
	Entity               *MetaEntity `protobuf:"bytes,1,opt,name=entity,proto3" json:"entity,omitempty"`
	XXX_NoUnkeyedLiteral struct{}    `json:"-"`
	XXX_unrecognized     []byte      `json:"-"`
	XXX_sizecache        int32       `json:"-"`
}

func (m *MetaGetEntityResponse) Reset()         { *m = MetaGetEntityResponse{} }
func (m *MetaGetEntityResponse) String() string { return proto.CompactTextString(m) }
func (*MetaGetEntityResponse) ProtoMessage()    {}
func (*MetaGetEntityResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_3b5ea8fe65782bcc, []int{21}
}

func (m *MetaGetEntityResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_MetaGetEntityResponse.Unmarshal(m, b)
}
func (m *MetaGetEntityResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_MetaGetEntityResponse.Marshal(b, m, deterministic)
}
func (m *MetaGetEntityResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MetaGetEntityResponse.Merge(m, src)
}
func (m *MetaGetEntityResponse) XXX_Size() int {
	return xxx_messageInfo_MetaGetEntityResponse.Size(m)
}
func (m *MetaGetEntityResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_MetaGetEntityResponse.DiscardUnknown(m)
}

var xxx_messageInfo_MetaGetEntityResponse proto.InternalMessageInfo

func (m *MetaGetEntityResponse) GetEntity() *MetaEntity {
	if m != nil {
		return m.Entity
	}
	return nil
}

type MetaUpdateEntityRequest struct {
	Entity               *MetaEntity `protobuf:"bytes,1,opt,name=entity,proto3" json:"entity,omitempty"`
	XXX_NoUnkeyedLiteral struct{}    `json:"-"`
	XXX_unrecognized     []byte      `json:"-"`
	XXX_sizecache        int32       `json:"-"`
}

func (m *MetaUpdateEntityRequest) Reset()         { *m = MetaUpdateEntityRequest{} }
func (m *MetaUpdateEntityRequest) String() string { return proto.CompactTextString(m) }
func (*MetaUpdateEntityRequest) ProtoMessage()    {}
func (*MetaUpdateEntityRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_3b5ea8fe65782bcc, []int{22}
}

func (m *MetaUpdateEntityRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_MetaUpdateEntityRequest.Unmarshal(m, b)
}
func (m *MetaUpdateEntityRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_MetaUpdateEntityRequest.Marshal(b, m, deterministic)
}
func (m *MetaUpdateEntityRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MetaUpdateEntityRequest.Merge(m, src)
}
func (m *MetaUpdateEntityRequest) XXX_Size() int {
	return xxx_messageInfo_MetaUpdateEntityRequest.Size(m)
}
func (m *MetaUpdateEntityRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_MetaUpdateEntityRequest.DiscardUnknown(m)
}

var xxx_messageInfo_MetaUpdateEntityRequest proto.InternalMessageInfo

func (m *MetaUpdateEntityRequest) GetEntity() *MetaEntity {
	if m != nil {
		return m.Entity
	}
	return nil
}

type MetaUpdateEntityResponse struct {
	Entity               *MetaEntity `protobuf:"bytes,1,opt,name=entity,proto3" json:"entity,omitempty"`
	XXX_NoUnkeyedLiteral struct{}    `json:"-"`
	XXX_unrecognized     []byte      `json:"-"`
	XXX_sizecache        int32       `json:"-"`
}

func (m *MetaUpdateEntityResponse) Reset()         { *m = MetaUpdateEntityResponse{} }
func (m *MetaUpdateEntityResponse) String() string { return proto.CompactTextString(m) }
func (*MetaUpdateEntityResponse) ProtoMessage()    {}
func (*MetaUpdateEntityResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_3b5ea8fe65782bcc, []int{23}
}

func (m *MetaUpdateEntityResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_MetaUpdateEntityResponse.Unmarshal(m, b)
}
func (m *MetaUpdateEntityResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_MetaUpdateEntityResponse.Marshal(b, m, deterministic)
}
func (m *MetaUpdateEntityResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MetaUpdateEntityResponse.Merge(m, src)
}
func (m *MetaUpdateEntityResponse) XXX_Size() int {
	return xxx_messageInfo_MetaUpdateEntityResponse.Size(m)
}
func (m *MetaUpdateEntityResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_MetaUpdateEntityResponse.DiscardUnknown(m)
}

var xxx_messageInfo_MetaUpdateEntityResponse proto.InternalMessageInfo

func (m *MetaUpdateEntityResponse) GetEntity() *MetaEntity {
	if m != nil {
		return m.Entity
	}
	return nil
}

type MetaCreateEntityRequest struct {
	Entity               *MetaEntity `protobuf:"bytes,1,opt,name=entity,proto3" json:"entity,omitempty"`
	KindName             string      `protobuf:"bytes,2,opt,name=kindName,proto3" json:"kindName,omitempty"`
	XXX_NoUnkeyedLiteral struct{}    `json:"-"`
	XXX_unrecognized     []byte      `json:"-"`
	XXX_sizecache        int32       `json:"-"`
}

func (m *MetaCreateEntityRequest) Reset()         { *m = MetaCreateEntityRequest{} }
func (m *MetaCreateEntityRequest) String() string { return proto.CompactTextString(m) }
func (*MetaCreateEntityRequest) ProtoMessage()    {}
func (*MetaCreateEntityRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_3b5ea8fe65782bcc, []int{24}
}

func (m *MetaCreateEntityRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_MetaCreateEntityRequest.Unmarshal(m, b)
}
func (m *MetaCreateEntityRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_MetaCreateEntityRequest.Marshal(b, m, deterministic)
}
func (m *MetaCreateEntityRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MetaCreateEntityRequest.Merge(m, src)
}
func (m *MetaCreateEntityRequest) XXX_Size() int {
	return xxx_messageInfo_MetaCreateEntityRequest.Size(m)
}
func (m *MetaCreateEntityRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_MetaCreateEntityRequest.DiscardUnknown(m)
}

var xxx_messageInfo_MetaCreateEntityRequest proto.InternalMessageInfo

func (m *MetaCreateEntityRequest) GetEntity() *MetaEntity {
	if m != nil {
		return m.Entity
	}
	return nil
}

func (m *MetaCreateEntityRequest) GetKindName() string {
	if m != nil {
		return m.KindName
	}
	return ""
}

type MetaCreateEntityResponse struct {
	Entity               *MetaEntity `protobuf:"bytes,1,opt,name=entity,proto3" json:"entity,omitempty"`
	XXX_NoUnkeyedLiteral struct{}    `json:"-"`
	XXX_unrecognized     []byte      `json:"-"`
	XXX_sizecache        int32       `json:"-"`
}

func (m *MetaCreateEntityResponse) Reset()         { *m = MetaCreateEntityResponse{} }
func (m *MetaCreateEntityResponse) String() string { return proto.CompactTextString(m) }
func (*MetaCreateEntityResponse) ProtoMessage()    {}
func (*MetaCreateEntityResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_3b5ea8fe65782bcc, []int{25}
}

func (m *MetaCreateEntityResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_MetaCreateEntityResponse.Unmarshal(m, b)
}
func (m *MetaCreateEntityResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_MetaCreateEntityResponse.Marshal(b, m, deterministic)
}
func (m *MetaCreateEntityResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MetaCreateEntityResponse.Merge(m, src)
}
func (m *MetaCreateEntityResponse) XXX_Size() int {
	return xxx_messageInfo_MetaCreateEntityResponse.Size(m)
}
func (m *MetaCreateEntityResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_MetaCreateEntityResponse.DiscardUnknown(m)
}

var xxx_messageInfo_MetaCreateEntityResponse proto.InternalMessageInfo

func (m *MetaCreateEntityResponse) GetEntity() *MetaEntity {
	if m != nil {
		return m.Entity
	}
	return nil
}

type MetaDeleteEntityRequest struct {
	Key                  *Key     `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`
	KindName             string   `protobuf:"bytes,2,opt,name=kindName,proto3" json:"kindName,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *MetaDeleteEntityRequest) Reset()         { *m = MetaDeleteEntityRequest{} }
func (m *MetaDeleteEntityRequest) String() string { return proto.CompactTextString(m) }
func (*MetaDeleteEntityRequest) ProtoMessage()    {}
func (*MetaDeleteEntityRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_3b5ea8fe65782bcc, []int{26}
}

func (m *MetaDeleteEntityRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_MetaDeleteEntityRequest.Unmarshal(m, b)
}
func (m *MetaDeleteEntityRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_MetaDeleteEntityRequest.Marshal(b, m, deterministic)
}
func (m *MetaDeleteEntityRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MetaDeleteEntityRequest.Merge(m, src)
}
func (m *MetaDeleteEntityRequest) XXX_Size() int {
	return xxx_messageInfo_MetaDeleteEntityRequest.Size(m)
}
func (m *MetaDeleteEntityRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_MetaDeleteEntityRequest.DiscardUnknown(m)
}

var xxx_messageInfo_MetaDeleteEntityRequest proto.InternalMessageInfo

func (m *MetaDeleteEntityRequest) GetKey() *Key {
	if m != nil {
		return m.Key
	}
	return nil
}

func (m *MetaDeleteEntityRequest) GetKindName() string {
	if m != nil {
		return m.KindName
	}
	return ""
}

type MetaDeleteEntityResponse struct {
	Entity               *MetaEntity `protobuf:"bytes,1,opt,name=entity,proto3" json:"entity,omitempty"`
	XXX_NoUnkeyedLiteral struct{}    `json:"-"`
	XXX_unrecognized     []byte      `json:"-"`
	XXX_sizecache        int32       `json:"-"`
}

func (m *MetaDeleteEntityResponse) Reset()         { *m = MetaDeleteEntityResponse{} }
func (m *MetaDeleteEntityResponse) String() string { return proto.CompactTextString(m) }
func (*MetaDeleteEntityResponse) ProtoMessage()    {}
func (*MetaDeleteEntityResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_3b5ea8fe65782bcc, []int{27}
}

func (m *MetaDeleteEntityResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_MetaDeleteEntityResponse.Unmarshal(m, b)
}
func (m *MetaDeleteEntityResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_MetaDeleteEntityResponse.Marshal(b, m, deterministic)
}
func (m *MetaDeleteEntityResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MetaDeleteEntityResponse.Merge(m, src)
}
func (m *MetaDeleteEntityResponse) XXX_Size() int {
	return xxx_messageInfo_MetaDeleteEntityResponse.Size(m)
}
func (m *MetaDeleteEntityResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_MetaDeleteEntityResponse.DiscardUnknown(m)
}

var xxx_messageInfo_MetaDeleteEntityResponse proto.InternalMessageInfo

func (m *MetaDeleteEntityResponse) GetEntity() *MetaEntity {
	if m != nil {
		return m.Entity
	}
	return nil
}

type MetaTransaction struct {
	Operations           []*MetaOperation `protobuf:"bytes,1,rep,name=operations,proto3" json:"operations,omitempty"`
	XXX_NoUnkeyedLiteral struct{}         `json:"-"`
	XXX_unrecognized     []byte           `json:"-"`
	XXX_sizecache        int32            `json:"-"`
}

func (m *MetaTransaction) Reset()         { *m = MetaTransaction{} }
func (m *MetaTransaction) String() string { return proto.CompactTextString(m) }
func (*MetaTransaction) ProtoMessage()    {}
func (*MetaTransaction) Descriptor() ([]byte, []int) {
	return fileDescriptor_3b5ea8fe65782bcc, []int{28}
}

func (m *MetaTransaction) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_MetaTransaction.Unmarshal(m, b)
}
func (m *MetaTransaction) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_MetaTransaction.Marshal(b, m, deterministic)
}
func (m *MetaTransaction) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MetaTransaction.Merge(m, src)
}
func (m *MetaTransaction) XXX_Size() int {
	return xxx_messageInfo_MetaTransaction.Size(m)
}
func (m *MetaTransaction) XXX_DiscardUnknown() {
	xxx_messageInfo_MetaTransaction.DiscardUnknown(m)
}

var xxx_messageInfo_MetaTransaction proto.InternalMessageInfo

func (m *MetaTransaction) GetOperations() []*MetaOperation {
	if m != nil {
		return m.Operations
	}
	return nil
}

type MetaOperation struct {
	// Types that are valid to be assigned to Operation:
	//	*MetaOperation_ListRequest
	//	*MetaOperation_GetRequest
	//	*MetaOperation_UpdateRequest
	//	*MetaOperation_CreateRequest
	//	*MetaOperation_DeleteRequest
	Operation            isMetaOperation_Operation `protobuf_oneof:"operation"`
	XXX_NoUnkeyedLiteral struct{}                  `json:"-"`
	XXX_unrecognized     []byte                    `json:"-"`
	XXX_sizecache        int32                     `json:"-"`
}

func (m *MetaOperation) Reset()         { *m = MetaOperation{} }
func (m *MetaOperation) String() string { return proto.CompactTextString(m) }
func (*MetaOperation) ProtoMessage()    {}
func (*MetaOperation) Descriptor() ([]byte, []int) {
	return fileDescriptor_3b5ea8fe65782bcc, []int{29}
}

func (m *MetaOperation) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_MetaOperation.Unmarshal(m, b)
}
func (m *MetaOperation) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_MetaOperation.Marshal(b, m, deterministic)
}
func (m *MetaOperation) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MetaOperation.Merge(m, src)
}
func (m *MetaOperation) XXX_Size() int {
	return xxx_messageInfo_MetaOperation.Size(m)
}
func (m *MetaOperation) XXX_DiscardUnknown() {
	xxx_messageInfo_MetaOperation.DiscardUnknown(m)
}

var xxx_messageInfo_MetaOperation proto.InternalMessageInfo

type isMetaOperation_Operation interface {
	isMetaOperation_Operation()
}

type MetaOperation_ListRequest struct {
	ListRequest *MetaListEntitiesRequest `protobuf:"bytes,1,opt,name=listRequest,proto3,oneof"`
}

type MetaOperation_GetRequest struct {
	GetRequest *MetaGetEntityRequest `protobuf:"bytes,2,opt,name=getRequest,proto3,oneof"`
}

type MetaOperation_UpdateRequest struct {
	UpdateRequest *MetaUpdateEntityRequest `protobuf:"bytes,3,opt,name=updateRequest,proto3,oneof"`
}

type MetaOperation_CreateRequest struct {
	CreateRequest *MetaCreateEntityRequest `protobuf:"bytes,4,opt,name=createRequest,proto3,oneof"`
}

type MetaOperation_DeleteRequest struct {
	DeleteRequest *MetaDeleteEntityRequest `protobuf:"bytes,5,opt,name=deleteRequest,proto3,oneof"`
}

func (*MetaOperation_ListRequest) isMetaOperation_Operation() {}

func (*MetaOperation_GetRequest) isMetaOperation_Operation() {}

func (*MetaOperation_UpdateRequest) isMetaOperation_Operation() {}

func (*MetaOperation_CreateRequest) isMetaOperation_Operation() {}

func (*MetaOperation_DeleteRequest) isMetaOperation_Operation() {}

func (m *MetaOperation) GetOperation() isMetaOperation_Operation {
	if m != nil {
		return m.Operation
	}
	return nil
}

func (m *MetaOperation) GetListRequest() *MetaListEntitiesRequest {
	if x, ok := m.GetOperation().(*MetaOperation_ListRequest); ok {
		return x.ListRequest
	}
	return nil
}

func (m *MetaOperation) GetGetRequest() *MetaGetEntityRequest {
	if x, ok := m.GetOperation().(*MetaOperation_GetRequest); ok {
		return x.GetRequest
	}
	return nil
}

func (m *MetaOperation) GetUpdateRequest() *MetaUpdateEntityRequest {
	if x, ok := m.GetOperation().(*MetaOperation_UpdateRequest); ok {
		return x.UpdateRequest
	}
	return nil
}

func (m *MetaOperation) GetCreateRequest() *MetaCreateEntityRequest {
	if x, ok := m.GetOperation().(*MetaOperation_CreateRequest); ok {
		return x.CreateRequest
	}
	return nil
}

func (m *MetaOperation) GetDeleteRequest() *MetaDeleteEntityRequest {
	if x, ok := m.GetOperation().(*MetaOperation_DeleteRequest); ok {
		return x.DeleteRequest
	}
	return nil
}

// XXX_OneofWrappers is for the internal use of the proto package.
func (*MetaOperation) XXX_OneofWrappers() []interface{} {
	return []interface{}{
		(*MetaOperation_ListRequest)(nil),
		(*MetaOperation_GetRequest)(nil),
		(*MetaOperation_UpdateRequest)(nil),
		(*MetaOperation_CreateRequest)(nil),
		(*MetaOperation_DeleteRequest)(nil),
	}
}

type MetaTransactionResult struct {
	OperationResults     []*MetaOperationResult `protobuf:"bytes,1,rep,name=operationResults,proto3" json:"operationResults,omitempty"`
	XXX_NoUnkeyedLiteral struct{}               `json:"-"`
	XXX_unrecognized     []byte                 `json:"-"`
	XXX_sizecache        int32                  `json:"-"`
}

func (m *MetaTransactionResult) Reset()         { *m = MetaTransactionResult{} }
func (m *MetaTransactionResult) String() string { return proto.CompactTextString(m) }
func (*MetaTransactionResult) ProtoMessage()    {}
func (*MetaTransactionResult) Descriptor() ([]byte, []int) {
	return fileDescriptor_3b5ea8fe65782bcc, []int{30}
}

func (m *MetaTransactionResult) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_MetaTransactionResult.Unmarshal(m, b)
}
func (m *MetaTransactionResult) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_MetaTransactionResult.Marshal(b, m, deterministic)
}
func (m *MetaTransactionResult) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MetaTransactionResult.Merge(m, src)
}
func (m *MetaTransactionResult) XXX_Size() int {
	return xxx_messageInfo_MetaTransactionResult.Size(m)
}
func (m *MetaTransactionResult) XXX_DiscardUnknown() {
	xxx_messageInfo_MetaTransactionResult.DiscardUnknown(m)
}

var xxx_messageInfo_MetaTransactionResult proto.InternalMessageInfo

func (m *MetaTransactionResult) GetOperationResults() []*MetaOperationResult {
	if m != nil {
		return m.OperationResults
	}
	return nil
}

type MetaOperationResultError struct {
	ErrorMessage         string   `protobuf:"bytes,1,opt,name=errorMessage,proto3" json:"errorMessage,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *MetaOperationResultError) Reset()         { *m = MetaOperationResultError{} }
func (m *MetaOperationResultError) String() string { return proto.CompactTextString(m) }
func (*MetaOperationResultError) ProtoMessage()    {}
func (*MetaOperationResultError) Descriptor() ([]byte, []int) {
	return fileDescriptor_3b5ea8fe65782bcc, []int{31}
}

func (m *MetaOperationResultError) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_MetaOperationResultError.Unmarshal(m, b)
}
func (m *MetaOperationResultError) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_MetaOperationResultError.Marshal(b, m, deterministic)
}
func (m *MetaOperationResultError) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MetaOperationResultError.Merge(m, src)
}
func (m *MetaOperationResultError) XXX_Size() int {
	return xxx_messageInfo_MetaOperationResultError.Size(m)
}
func (m *MetaOperationResultError) XXX_DiscardUnknown() {
	xxx_messageInfo_MetaOperationResultError.DiscardUnknown(m)
}

var xxx_messageInfo_MetaOperationResultError proto.InternalMessageInfo

func (m *MetaOperationResultError) GetErrorMessage() string {
	if m != nil {
		return m.ErrorMessage
	}
	return ""
}

type MetaOperationResult struct {
	Error *MetaOperationResultError `protobuf:"bytes,1,opt,name=error,proto3" json:"error,omitempty"`
	// Types that are valid to be assigned to Operation:
	//	*MetaOperationResult_ListResponse
	//	*MetaOperationResult_GetResponse
	//	*MetaOperationResult_UpdateResponse
	//	*MetaOperationResult_CreateResponse
	//	*MetaOperationResult_DeleteResponse
	Operation            isMetaOperationResult_Operation `protobuf_oneof:"operation"`
	XXX_NoUnkeyedLiteral struct{}                        `json:"-"`
	XXX_unrecognized     []byte                          `json:"-"`
	XXX_sizecache        int32                           `json:"-"`
}

func (m *MetaOperationResult) Reset()         { *m = MetaOperationResult{} }
func (m *MetaOperationResult) String() string { return proto.CompactTextString(m) }
func (*MetaOperationResult) ProtoMessage()    {}
func (*MetaOperationResult) Descriptor() ([]byte, []int) {
	return fileDescriptor_3b5ea8fe65782bcc, []int{32}
}

func (m *MetaOperationResult) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_MetaOperationResult.Unmarshal(m, b)
}
func (m *MetaOperationResult) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_MetaOperationResult.Marshal(b, m, deterministic)
}
func (m *MetaOperationResult) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MetaOperationResult.Merge(m, src)
}
func (m *MetaOperationResult) XXX_Size() int {
	return xxx_messageInfo_MetaOperationResult.Size(m)
}
func (m *MetaOperationResult) XXX_DiscardUnknown() {
	xxx_messageInfo_MetaOperationResult.DiscardUnknown(m)
}

var xxx_messageInfo_MetaOperationResult proto.InternalMessageInfo

func (m *MetaOperationResult) GetError() *MetaOperationResultError {
	if m != nil {
		return m.Error
	}
	return nil
}

type isMetaOperationResult_Operation interface {
	isMetaOperationResult_Operation()
}

type MetaOperationResult_ListResponse struct {
	ListResponse *MetaListEntitiesResponse `protobuf:"bytes,2,opt,name=listResponse,proto3,oneof"`
}

type MetaOperationResult_GetResponse struct {
	GetResponse *MetaGetEntityResponse `protobuf:"bytes,3,opt,name=getResponse,proto3,oneof"`
}

type MetaOperationResult_UpdateResponse struct {
	UpdateResponse *MetaUpdateEntityResponse `protobuf:"bytes,4,opt,name=updateResponse,proto3,oneof"`
}

type MetaOperationResult_CreateResponse struct {
	CreateResponse *MetaCreateEntityResponse `protobuf:"bytes,5,opt,name=createResponse,proto3,oneof"`
}

type MetaOperationResult_DeleteResponse struct {
	DeleteResponse *MetaDeleteEntityResponse `protobuf:"bytes,6,opt,name=deleteResponse,proto3,oneof"`
}

func (*MetaOperationResult_ListResponse) isMetaOperationResult_Operation() {}

func (*MetaOperationResult_GetResponse) isMetaOperationResult_Operation() {}

func (*MetaOperationResult_UpdateResponse) isMetaOperationResult_Operation() {}

func (*MetaOperationResult_CreateResponse) isMetaOperationResult_Operation() {}

func (*MetaOperationResult_DeleteResponse) isMetaOperationResult_Operation() {}

func (m *MetaOperationResult) GetOperation() isMetaOperationResult_Operation {
	if m != nil {
		return m.Operation
	}
	return nil
}

func (m *MetaOperationResult) GetListResponse() *MetaListEntitiesResponse {
	if x, ok := m.GetOperation().(*MetaOperationResult_ListResponse); ok {
		return x.ListResponse
	}
	return nil
}

func (m *MetaOperationResult) GetGetResponse() *MetaGetEntityResponse {
	if x, ok := m.GetOperation().(*MetaOperationResult_GetResponse); ok {
		return x.GetResponse
	}
	return nil
}

func (m *MetaOperationResult) GetUpdateResponse() *MetaUpdateEntityResponse {
	if x, ok := m.GetOperation().(*MetaOperationResult_UpdateResponse); ok {
		return x.UpdateResponse
	}
	return nil
}

func (m *MetaOperationResult) GetCreateResponse() *MetaCreateEntityResponse {
	if x, ok := m.GetOperation().(*MetaOperationResult_CreateResponse); ok {
		return x.CreateResponse
	}
	return nil
}

func (m *MetaOperationResult) GetDeleteResponse() *MetaDeleteEntityResponse {
	if x, ok := m.GetOperation().(*MetaOperationResult_DeleteResponse); ok {
		return x.DeleteResponse
	}
	return nil
}

// XXX_OneofWrappers is for the internal use of the proto package.
func (*MetaOperationResult) XXX_OneofWrappers() []interface{} {
	return []interface{}{
		(*MetaOperationResult_ListResponse)(nil),
		(*MetaOperationResult_GetResponse)(nil),
		(*MetaOperationResult_UpdateResponse)(nil),
		(*MetaOperationResult_CreateResponse)(nil),
		(*MetaOperationResult_DeleteResponse)(nil),
	}
}

func init() {
	proto.RegisterEnum("meta.ValueType", ValueType_name, ValueType_value)
	proto.RegisterEnum("meta.SchemaFieldEditorInfoType", SchemaFieldEditorInfoType_name, SchemaFieldEditorInfoType_value)
	proto.RegisterEnum("meta.SchemaIndexType", SchemaIndexType_name, SchemaIndexType_value)
	proto.RegisterType((*PartitionId)(nil), "meta.PartitionId")
	proto.RegisterType((*PathElement)(nil), "meta.PathElement")
	proto.RegisterType((*Key)(nil), "meta.Key")
	proto.RegisterType((*Value)(nil), "meta.Value")
	proto.RegisterType((*SchemaField)(nil), "meta.SchemaField")
	proto.RegisterType((*SchemaFieldEditorInfo)(nil), "meta.SchemaFieldEditorInfo")
	proto.RegisterType((*SchemaKindEditor)(nil), "meta.SchemaKindEditor")
	proto.RegisterType((*SchemaKind)(nil), "meta.SchemaKind")
	proto.RegisterType((*SchemaIndex)(nil), "meta.SchemaIndex")
	proto.RegisterType((*SchemaComputedIndex)(nil), "meta.SchemaComputedIndex")
	proto.RegisterType((*SchemaComputedIndexFnv64A)(nil), "meta.SchemaComputedIndexFnv64a")
	proto.RegisterType((*SchemaComputedIndexFnv64APair)(nil), "meta.SchemaComputedIndexFnv64aPair")
	proto.RegisterType((*Schema)(nil), "meta.Schema")
	proto.RegisterMapType((map[string]*SchemaKind)(nil), "meta.Schema.KindsEntry")
	proto.RegisterType((*GetSchemaRequest)(nil), "meta.GetSchemaRequest")
	proto.RegisterType((*GetSchemaResponse)(nil), "meta.GetSchemaResponse")
	proto.RegisterType((*MetaListEntitiesRequest)(nil), "meta.MetaListEntitiesRequest")
	proto.RegisterType((*MetaListEntitiesResponse)(nil), "meta.MetaListEntitiesResponse")
	proto.RegisterType((*MetaEntity)(nil), "meta.MetaEntity")
	proto.RegisterType((*GetDefaultPartitionIdRequest)(nil), "meta.GetDefaultPartitionIdRequest")
	proto.RegisterType((*GetDefaultPartitionIdResponse)(nil), "meta.GetDefaultPartitionIdResponse")
	proto.RegisterType((*MetaGetEntityRequest)(nil), "meta.MetaGetEntityRequest")
	proto.RegisterType((*MetaGetEntityResponse)(nil), "meta.MetaGetEntityResponse")
	proto.RegisterType((*MetaUpdateEntityRequest)(nil), "meta.MetaUpdateEntityRequest")
	proto.RegisterType((*MetaUpdateEntityResponse)(nil), "meta.MetaUpdateEntityResponse")
	proto.RegisterType((*MetaCreateEntityRequest)(nil), "meta.MetaCreateEntityRequest")
	proto.RegisterType((*MetaCreateEntityResponse)(nil), "meta.MetaCreateEntityResponse")
	proto.RegisterType((*MetaDeleteEntityRequest)(nil), "meta.MetaDeleteEntityRequest")
	proto.RegisterType((*MetaDeleteEntityResponse)(nil), "meta.MetaDeleteEntityResponse")
	proto.RegisterType((*MetaTransaction)(nil), "meta.MetaTransaction")
	proto.RegisterType((*MetaOperation)(nil), "meta.MetaOperation")
	proto.RegisterType((*MetaTransactionResult)(nil), "meta.MetaTransactionResult")
	proto.RegisterType((*MetaOperationResultError)(nil), "meta.MetaOperationResultError")
	proto.RegisterType((*MetaOperationResult)(nil), "meta.MetaOperationResult")
}

func init() { proto.RegisterFile("meta.proto", fileDescriptor_3b5ea8fe65782bcc) }

var fileDescriptor_3b5ea8fe65782bcc = []byte{
	// 1640 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x9c, 0x58, 0xcb, 0x72, 0xdb, 0xc6,
	0x12, 0x25, 0xf8, 0x66, 0x53, 0x0f, 0xb8, 0x6d, 0xc9, 0x34, 0x6d, 0xcb, 0x2c, 0xe8, 0xda, 0x25,
	0xdb, 0xf7, 0xaa, 0xca, 0x92, 0xcb, 0xf7, 0xfa, 0x96, 0x93, 0x94, 0xf5, 0x32, 0x15, 0xc5, 0x8f,
	0x1a, 0x3b, 0x59, 0xc6, 0x81, 0x88, 0xa1, 0x84, 0x12, 0x08, 0x20, 0xc0, 0xd0, 0x36, 0x37, 0xf9,
	0x8d, 0x7c, 0x41, 0xf2, 0x01, 0x59, 0x65, 0x93, 0x45, 0x3e, 0x22, 0x3f, 0x92, 0x45, 0xd6, 0xa9,
	0x79, 0x00, 0x1c, 0x80, 0x10, 0x15, 0x7b, 0x87, 0xe9, 0xe9, 0x3e, 0x73, 0xa6, 0xfb, 0xb0, 0x67,
	0x86, 0x00, 0x23, 0xca, 0xec, 0xcd, 0x30, 0x0a, 0x58, 0x80, 0x55, 0xfe, 0x6d, 0xdd, 0x87, 0xf6,
	0x2b, 0x3b, 0x62, 0x2e, 0x73, 0x03, 0xff, 0xd0, 0xc1, 0x1b, 0xd0, 0xf2, 0xed, 0x11, 0x8d, 0x43,
	0x7b, 0x40, 0x3b, 0x46, 0xcf, 0xd8, 0x68, 0x91, 0xa9, 0xc1, 0x7a, 0xcd, 0x9d, 0xd9, 0xe9, 0xbe,
	0x47, 0x47, 0xd4, 0x67, 0x88, 0x50, 0x3d, 0x73, 0x7d, 0x47, 0xf9, 0x89, 0x6f, 0x34, 0xa1, 0xec,
	0x3a, 0x9d, 0x72, 0xcf, 0xd8, 0xa8, 0xf4, 0x4b, 0xa4, 0xec, 0x3a, 0x78, 0x05, 0xaa, 0x1c, 0xa1,
	0x53, 0xe1, 0x5e, 0xfd, 0x12, 0x11, 0xa3, 0x9d, 0x26, 0xd4, 0x5d, 0xe7, 0xcd, 0x24, 0xa4, 0x96,
	0x0d, 0x95, 0x23, 0x3a, 0xc1, 0x6d, 0x68, 0x87, 0x53, 0x22, 0x02, 0xb3, 0xbd, 0x75, 0x69, 0x53,
	0x10, 0xd6, 0x18, 0x12, 0xdd, 0x0b, 0x6f, 0x43, 0x35, 0xb4, 0xd9, 0x69, 0xa7, 0xdc, 0xab, 0xe8,
	0xde, 0x29, 0x45, 0x22, 0xa6, 0xad, 0x3f, 0xca, 0x50, 0xfb, 0xc6, 0xf6, 0xc6, 0x14, 0x97, 0x04,
	0x3d, 0x0e, 0x5e, 0x13, 0xe4, 0xd6, 0xa1, 0xca, 0x26, 0x21, 0x15, 0x84, 0x97, 0xb6, 0x96, 0x25,
	0x80, 0x70, 0xe5, 0xdc, 0x88, 0x98, 0xc4, 0x1e, 0xb4, 0x9d, 0x60, 0x7c, 0xec, 0x51, 0x31, 0x21,
	0x36, 0x62, 0x10, 0xdd, 0x84, 0x6b, 0x00, 0xae, 0xcf, 0x1e, 0x3d, 0x94, 0x0e, 0x55, 0xbe, 0x7b,
	0xa2, 0x59, 0x38, 0x42, 0xcc, 0x22, 0xd7, 0x3f, 0x91, 0x0e, 0x35, 0x91, 0x30, 0xdd, 0x84, 0x77,
	0x60, 0x89, 0xb9, 0x23, 0x1a, 0x33, 0x7b, 0x14, 0x4a, 0xa7, 0x7a, 0xcf, 0xd8, 0x58, 0x20, 0x39,
	0x2b, 0x5a, 0xb0, 0x70, 0x1c, 0x04, 0x1e, 0xb5, 0x7d, 0xe9, 0xd5, 0xe8, 0x19, 0x1b, 0x4d, 0x92,
	0xb1, 0x71, 0x36, 0xc7, 0x13, 0x46, 0x63, 0xe9, 0xd1, 0x14, 0x38, 0x9a, 0x05, 0x6f, 0x43, 0xf3,
	0x8c, 0x4e, 0xe4, 0x6c, 0x4b, 0xe4, 0xb9, 0x25, 0x37, 0x7e, 0x44, 0x27, 0x24, 0x9d, 0xe2, 0xa4,
	0xc7, 0xda, 0xae, 0xa0, 0x67, 0x6c, 0x54, 0x89, 0x6e, 0xb2, 0x7e, 0x37, 0xa0, 0xfd, 0x7a, 0x70,
	0x4a, 0x47, 0xf6, 0x81, 0x4b, 0x3d, 0x67, 0x26, 0xbb, 0xa8, 0x4a, 0x5f, 0x96, 0x02, 0xe1, 0xdf,
	0x69, 0xc6, 0x2b, 0xf3, 0x32, 0xde, 0x81, 0xc6, 0x20, 0x18, 0xf1, 0x0a, 0x8a, 0x64, 0xb6, 0x48,
	0x32, 0xc4, 0x6d, 0xa8, 0x53, 0xc7, 0x65, 0x41, 0x24, 0x92, 0xd8, 0xde, 0xba, 0x2e, 0x01, 0x34,
	0x16, 0xfb, 0x62, 0xfa, 0xd0, 0x1f, 0x06, 0x44, 0xb9, 0x62, 0x17, 0x9a, 0x11, 0xb5, 0x9d, 0xc0,
	0xf7, 0x26, 0x22, 0xad, 0x4d, 0x92, 0x8e, 0xad, 0x5f, 0x0d, 0x58, 0x29, 0x8c, 0x16, 0x65, 0x77,
	0xe3, 0xd0, 0xb3, 0x27, 0x2f, 0xf8, 0x26, 0xa4, 0xca, 0x75, 0x13, 0x6e, 0x67, 0xd4, 0x73, 0x6b,
	0x0e, 0x15, 0x6d, 0x6f, 0x77, 0x60, 0x49, 0xd2, 0x22, 0x09, 0xa5, 0x8a, 0xa0, 0x94, 0xb3, 0xf2,
	0xe5, 0x87, 0x41, 0x44, 0xdd, 0x13, 0x9f, 0x07, 0xab, 0x3c, 0xe8, 0x26, 0xeb, 0x00, 0x4c, 0xb9,
	0xd8, 0x91, 0xeb, 0xab, 0xb5, 0xf8, 0x56, 0x63, 0xd7, 0x3f, 0x19, 0x7b, 0x76, 0xa4, 0x18, 0xa7,
	0x63, 0x5c, 0x85, 0x7a, 0xe8, 0x8d, 0x23, 0xdb, 0x53, 0x05, 0x51, 0x23, 0xeb, 0x17, 0x03, 0x60,
	0x0a, 0x84, 0x77, 0xa1, 0x3e, 0xe4, 0xec, 0xe3, 0xec, 0xcf, 0x4a, 0xdb, 0x17, 0x51, 0x0e, 0xb8,
	0x99, 0x56, 0xa3, 0x22, 0xaa, 0xb1, 0xaa, 0xbb, 0x4e, 0x59, 0xa5, 0x85, 0xb8, 0x0f, 0x0d, 0xd7,
	0x77, 0xe8, 0x07, 0x1a, 0x77, 0xaa, 0xb3, 0xd8, 0x87, 0x7c, 0x8a, 0x24, 0x1e, 0xbc, 0x17, 0xd9,
	0xfe, 0x80, 0xc6, 0x2c, 0x88, 0xe2, 0x4e, 0xad, 0x57, 0xe1, 0xbd, 0x28, 0x35, 0x58, 0x3f, 0xa7,
	0xda, 0x13, 0x61, 0xa9, 0xd6, 0x0c, 0x4d, 0x6b, 0x77, 0x33, 0xf5, 0x59, 0x99, 0x59, 0x4b, 0xab,
	0xca, 0x7f, 0xa1, 0x39, 0x08, 0x46, 0xe1, 0x98, 0x51, 0x47, 0xed, 0xe5, 0x9a, 0xee, 0xbe, 0xab,
	0xe6, 0x44, 0x58, 0xbf, 0x44, 0x52, 0x67, 0x5c, 0x85, 0x9a, 0x48, 0x86, 0x2c, 0x50, 0xbf, 0x44,
	0xe4, 0x70, 0xa7, 0x01, 0xb5, 0x77, 0xe2, 0x47, 0xf2, 0x93, 0x01, 0x97, 0x0b, 0x40, 0xf0, 0x31,
	0xd4, 0x87, 0xfe, 0xbb, 0x47, 0x0f, 0x6d, 0xd5, 0xeb, 0x6e, 0x9d, 0xbb, 0xde, 0x81, 0x70, 0xeb,
	0x97, 0x88, 0x0a, 0xc0, 0x03, 0x68, 0xcb, 0xaf, 0xb7, 0xa1, 0xed, 0x46, 0x62, 0x7b, 0xed, 0xad,
	0xf5, 0x0b, 0xe2, 0x5f, 0xd9, 0x6e, 0xd4, 0x2f, 0x11, 0x18, 0xa6, 0xa3, 0x9d, 0x36, 0xb4, 0x6c,
	0xef, 0x24, 0x88, 0x5c, 0x76, 0x3a, 0xb2, 0x1e, 0xc0, 0xb5, 0x73, 0x63, 0xf1, 0x4a, 0xb2, 0x4b,
	0x99, 0x5e, 0x39, 0xb0, 0x5e, 0xc2, 0xcd, 0xb9, 0xcb, 0x71, 0xc5, 0x09, 0xcf, 0x07, 0x2a, 0x4e,
	0x8d, 0x52, 0xfb, 0x56, 0xa2, 0x44, 0x39, 0xb2, 0x7e, 0x34, 0xa0, 0x2e, 0x11, 0x0b, 0xeb, 0xf9,
	0x1f, 0xa8, 0xf1, 0x43, 0x26, 0x11, 0xe6, 0x55, 0x7d, 0xc7, 0x9b, 0x5c, 0x6e, 0xf1, 0xbe, 0xcf,
	0xa2, 0x09, 0x91, 0x5e, 0xdd, 0x2f, 0x01, 0xa6, 0x46, 0x34, 0xa1, 0x72, 0x46, 0x27, 0x0a, 0x8f,
	0x7f, 0xe2, 0x1d, 0x55, 0x22, 0x95, 0x40, 0x33, 0x2f, 0x5e, 0x22, 0xa7, 0xff, 0x5f, 0xfe, 0x9f,
	0x61, 0x21, 0x98, 0xcf, 0x28, 0x93, 0x73, 0x84, 0x7e, 0x3f, 0xa6, 0x31, 0xb3, 0x1e, 0xc3, 0x25,
	0xcd, 0x16, 0x87, 0x81, 0x1f, 0x53, 0xfc, 0x17, 0xd4, 0x63, 0x61, 0x51, 0x65, 0x5d, 0xd0, 0x51,
	0x89, 0x9a, 0xb3, 0x6c, 0xb8, 0xfa, 0x9c, 0x32, 0xfb, 0x2b, 0x37, 0x66, 0xfb, 0x3e, 0x3f, 0xce,
	0x68, 0xac, 0x50, 0x79, 0xaa, 0x63, 0x66, 0x47, 0x4c, 0xc4, 0x2f, 0x10, 0x39, 0xe0, 0x56, 0xcf,
	0x1d, 0xb9, 0x4c, 0x70, 0x5d, 0x24, 0x72, 0xc0, 0x7f, 0xed, 0x7c, 0xab, 0x2f, 0xd2, 0xf3, 0x95,
	0xa4, 0x63, 0xeb, 0x07, 0xe8, 0xcc, 0x2e, 0xa1, 0x48, 0xf2, 0xe4, 0xd2, 0x0f, 0xc9, 0x12, 0xe2,
	0x9b, 0xf7, 0x9b, 0x51, 0x10, 0x51, 0x42, 0xe3, 0xb1, 0xc7, 0x62, 0xb1, 0x4e, 0x93, 0xe8, 0x26,
	0xfc, 0x37, 0x34, 0xa9, 0x42, 0xea, 0x54, 0x44, 0x05, 0x54, 0xca, 0xf8, 0x3a, 0x62, 0x8d, 0x09,
	0x49, 0x3d, 0xac, 0x17, 0x00, 0x53, 0x3b, 0x5e, 0x9f, 0x66, 0x3f, 0x73, 0xdc, 0x88, 0x42, 0xac,
	0x43, 0x5d, 0x64, 0x3a, 0x29, 0x6c, 0x5b, 0x3b, 0x15, 0x88, 0x9a, 0xb2, 0xd6, 0xe0, 0xc6, 0x33,
	0xca, 0xf6, 0xe8, 0xd0, 0x1e, 0x7b, 0x4c, 0xbf, 0x11, 0xa8, 0x6a, 0x7c, 0x06, 0x37, 0xcf, 0x99,
	0x57, 0x9b, 0x9e, 0x7f, 0xb7, 0x79, 0x09, 0x57, 0x38, 0xdd, 0x67, 0x94, 0xa9, 0x9d, 0xa8, 0x72,
	0xcc, 0x25, 0xae, 0xe7, 0xbf, 0x9c, 0xcb, 0xff, 0x53, 0x58, 0xc9, 0x01, 0x2a, 0x1e, 0x1b, 0x50,
	0x17, 0x49, 0x4a, 0x40, 0x67, 0x93, 0xa8, 0xe6, 0xad, 0x5d, 0xa9, 0x92, 0xaf, 0x43, 0xc7, 0x66,
	0x34, 0x4b, 0xeb, 0x9f, 0x83, 0xec, 0x49, 0x1d, 0x64, 0x41, 0x3e, 0x9a, 0xca, 0x5b, 0x49, 0x65,
	0x37, 0xa2, 0x9f, 0x4e, 0x65, 0x6e, 0xba, 0x14, 0xcd, 0xec, 0x02, 0x1f, 0x4d, 0x93, 0x48, 0x9a,
	0x7b, 0xd4, 0xa3, 0x79, 0x9a, 0x9f, 0x5c, 0x48, 0xc5, 0x2c, 0x8b, 0xf9, 0xd1, 0xcc, 0x0e, 0x60,
	0x99, 0x5b, 0xdf, 0x44, 0xb6, 0x1f, 0xdb, 0x03, 0x2e, 0x4d, 0xdc, 0x06, 0x08, 0x42, 0x1a, 0xd9,
	0x7c, 0x10, 0x77, 0x0c, 0x21, 0xfd, 0xcb, 0x53, 0x80, 0x97, 0xc9, 0x1c, 0xd1, 0xdc, 0xac, 0x3f,
	0xcb, 0xb0, 0x98, 0x99, 0xc5, 0xa7, 0xd0, 0xf6, 0xdc, 0x98, 0xa9, 0x7d, 0x2a, 0x22, 0x37, 0xa7,
	0x38, 0x05, 0x4d, 0xa6, 0x5f, 0x22, 0x7a, 0x0c, 0x3e, 0x01, 0x38, 0xa1, 0x29, 0x82, 0x6c, 0x87,
	0xdd, 0x29, 0x42, 0xfe, 0x47, 0xc1, 0x8f, 0x91, 0xa9, 0x3f, 0xee, 0xc3, 0xe2, 0x58, 0xa8, 0x2b,
	0x01, 0xa8, 0xe4, 0x29, 0x14, 0x28, 0xb8, 0x5f, 0x22, 0xd9, 0x28, 0x0e, 0x33, 0x10, 0xd5, 0x4f,
	0x60, 0xaa, 0x79, 0x98, 0x02, 0xf5, 0x71, 0x98, 0x4c, 0x14, 0x87, 0x71, 0x44, 0xa9, 0x12, 0x98,
	0x5a, 0x1e, 0xa6, 0x40, 0x1d, 0x1c, 0x26, 0x13, 0xc5, 0xcf, 0xc6, 0x34, 0xeb, 0xd6, 0xb7, 0xf2,
	0xb7, 0xac, 0x15, 0x4f, 0xf6, 0x44, 0xdc, 0x07, 0x33, 0xf5, 0x4a, 0x3a, 0xa7, 0x2c, 0xe4, 0xb5,
	0xa2, 0x42, 0x0a, 0x0f, 0x32, 0x13, 0x62, 0x7d, 0x2e, 0x25, 0x96, 0x73, 0xdc, 0x8f, 0xa2, 0x20,
	0xe2, 0x37, 0x7e, 0xca, 0x3f, 0x9e, 0xd3, 0x38, 0xb6, 0x4f, 0x92, 0xce, 0x95, 0xb1, 0x59, 0xbf,
	0x55, 0xe0, 0x72, 0x01, 0x00, 0x3e, 0x84, 0x9a, 0xf0, 0x53, 0xa2, 0x58, 0x3b, 0x97, 0x93, 0x58,
	0x8a, 0x48, 0x67, 0xdc, 0x83, 0x05, 0x29, 0x0e, 0x29, 0x72, 0xa5, 0x87, 0xb5, 0xf3, 0x14, 0x25,
	0xbd, 0xfa, 0x25, 0x92, 0x89, 0xc2, 0x2f, 0xa0, 0x2d, 0x34, 0xa2, 0x40, 0x2a, 0xfa, 0x75, 0xbd,
	0xb0, 0x31, 0x72, 0x51, 0x6a, 0x11, 0xd8, 0x87, 0xa5, 0x44, 0x20, 0x0a, 0xa3, 0x9a, 0x27, 0x52,
	0xd4, 0xd4, 0xfa, 0x25, 0x92, 0x8b, 0xe3, 0x48, 0x89, 0x46, 0x14, 0x52, 0x2d, 0x8f, 0x54, 0xd4,
	0x77, 0x38, 0x52, 0x36, 0x8e, 0x23, 0x25, 0x32, 0x51, 0x48, 0xf5, 0x3c, 0x52, 0x51, 0x9f, 0xe0,
	0x48, 0xd9, 0xb8, 0x8c, 0xbe, 0xee, 0xbd, 0x87, 0x56, 0xfa, 0x04, 0xc2, 0x36, 0x34, 0xc6, 0xfe,
	0x99, 0x1f, 0xbc, 0xf7, 0xcd, 0x12, 0x02, 0xd4, 0xe5, 0x43, 0xd3, 0x34, 0xb0, 0x05, 0x35, 0xf1,
	0xf8, 0x32, 0xcb, 0xdc, 0x2c, 0x5f, 0x8f, 0x66, 0x05, 0x17, 0xa1, 0x95, 0x3e, 0x12, 0xcd, 0x2a,
	0x0f, 0x57, 0xaf, 0x41, 0xb3, 0xc6, 0x43, 0xc4, 0xc3, 0xcf, 0xac, 0x63, 0x43, 0xf4, 0x3f, 0xb3,
	0xc1, 0x63, 0xe5, 0x23, 0xce, 0x6c, 0xde, 0xdb, 0x49, 0x2e, 0x7d, 0x05, 0xef, 0x15, 0x8e, 0xe4,
	0xc8, 0xe3, 0xd4, 0x2c, 0xe1, 0x02, 0x34, 0x43, 0x3b, 0x8e, 0xdf, 0x07, 0x91, 0x63, 0x1a, 0x1c,
	0xc3, 0x0b, 0x82, 0xb3, 0x71, 0x68, 0x96, 0xef, 0x6d, 0xc2, 0x72, 0xee, 0x4e, 0x8d, 0xcb, 0xd0,
	0x1e, 0xfb, 0x71, 0x48, 0x07, 0xee, 0xd0, 0xa5, 0x8e, 0xdc, 0xc6, 0x88, 0x8e, 0x82, 0x68, 0x62,
	0x1a, 0x5b, 0x7f, 0x55, 0x61, 0x75, 0x37, 0xf0, 0x87, 0xee, 0x09, 0xbf, 0xc9, 0x53, 0x9e, 0xb3,
	0xd7, 0x34, 0x7a, 0xe7, 0x0e, 0x28, 0x3e, 0x81, 0x56, 0x7a, 0xa3, 0x42, 0xf5, 0x98, 0xc8, 0x5f,
	0xbb, 0xba, 0x57, 0x67, 0xec, 0xaa, 0x38, 0x87, 0xd0, 0x4c, 0xd4, 0x89, 0xf3, 0xfb, 0x5f, 0xf7,
	0x02, 0x31, 0xe3, 0x0e, 0x34, 0x94, 0x46, 0x71, 0x4e, 0x1f, 0xec, 0xce, 0x93, 0x33, 0x1e, 0xc9,
	0x0b, 0x90, 0xd4, 0x28, 0xce, 0xef, 0x86, 0xdd, 0x0b, 0x44, 0x9d, 0x80, 0x49, 0x99, 0xe2, 0xfc,
	0x9e, 0xd8, 0xbd, 0x40, 0xd7, 0x09, 0x98, 0x54, 0x2a, 0xce, 0xef, 0x8c, 0xdd, 0x0b, 0xa4, 0x8d,
	0xdf, 0xc1, 0x4a, 0xe1, 0xbd, 0x0b, 0xad, 0xb4, 0x4e, 0xe7, 0x5e, 0xda, 0xba, 0xeb, 0x73, 0x7d,
	0xd4, 0x0a, 0x07, 0x60, 0x3e, 0x0d, 0x43, 0x6f, 0xa2, 0x9f, 0x9d, 0x2b, 0x53, 0x56, 0x9a, 0x59,
	0x2f, 0xc8, 0x4c, 0xb3, 0x3e, 0xae, 0x8b, 0x3f, 0xbe, 0xb6, 0xff, 0x0e, 0x00, 0x00, 0xff, 0xff,
	0x7a, 0x52, 0x07, 0x54, 0x06, 0x13, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// ConfigstoreMetaServiceClient is the client API for ConfigstoreMetaService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type ConfigstoreMetaServiceClient interface {
	GetSchema(ctx context.Context, in *GetSchemaRequest, opts ...grpc.CallOption) (*GetSchemaResponse, error)
	MetaList(ctx context.Context, in *MetaListEntitiesRequest, opts ...grpc.CallOption) (*MetaListEntitiesResponse, error)
	MetaGet(ctx context.Context, in *MetaGetEntityRequest, opts ...grpc.CallOption) (*MetaGetEntityResponse, error)
	MetaUpdate(ctx context.Context, in *MetaUpdateEntityRequest, opts ...grpc.CallOption) (*MetaUpdateEntityResponse, error)
	MetaCreate(ctx context.Context, in *MetaCreateEntityRequest, opts ...grpc.CallOption) (*MetaCreateEntityResponse, error)
	MetaDelete(ctx context.Context, in *MetaDeleteEntityRequest, opts ...grpc.CallOption) (*MetaDeleteEntityResponse, error)
	GetDefaultPartitionId(ctx context.Context, in *GetDefaultPartitionIdRequest, opts ...grpc.CallOption) (*GetDefaultPartitionIdResponse, error)
	ApplyTransaction(ctx context.Context, in *MetaTransaction, opts ...grpc.CallOption) (*MetaTransactionResult, error)
}

type configstoreMetaServiceClient struct {
	cc *grpc.ClientConn
}

func NewConfigstoreMetaServiceClient(cc *grpc.ClientConn) ConfigstoreMetaServiceClient {
	return &configstoreMetaServiceClient{cc}
}

func (c *configstoreMetaServiceClient) GetSchema(ctx context.Context, in *GetSchemaRequest, opts ...grpc.CallOption) (*GetSchemaResponse, error) {
	out := new(GetSchemaResponse)
	err := c.cc.Invoke(ctx, "/meta.ConfigstoreMetaService/GetSchema", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *configstoreMetaServiceClient) MetaList(ctx context.Context, in *MetaListEntitiesRequest, opts ...grpc.CallOption) (*MetaListEntitiesResponse, error) {
	out := new(MetaListEntitiesResponse)
	err := c.cc.Invoke(ctx, "/meta.ConfigstoreMetaService/MetaList", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *configstoreMetaServiceClient) MetaGet(ctx context.Context, in *MetaGetEntityRequest, opts ...grpc.CallOption) (*MetaGetEntityResponse, error) {
	out := new(MetaGetEntityResponse)
	err := c.cc.Invoke(ctx, "/meta.ConfigstoreMetaService/MetaGet", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *configstoreMetaServiceClient) MetaUpdate(ctx context.Context, in *MetaUpdateEntityRequest, opts ...grpc.CallOption) (*MetaUpdateEntityResponse, error) {
	out := new(MetaUpdateEntityResponse)
	err := c.cc.Invoke(ctx, "/meta.ConfigstoreMetaService/MetaUpdate", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *configstoreMetaServiceClient) MetaCreate(ctx context.Context, in *MetaCreateEntityRequest, opts ...grpc.CallOption) (*MetaCreateEntityResponse, error) {
	out := new(MetaCreateEntityResponse)
	err := c.cc.Invoke(ctx, "/meta.ConfigstoreMetaService/MetaCreate", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *configstoreMetaServiceClient) MetaDelete(ctx context.Context, in *MetaDeleteEntityRequest, opts ...grpc.CallOption) (*MetaDeleteEntityResponse, error) {
	out := new(MetaDeleteEntityResponse)
	err := c.cc.Invoke(ctx, "/meta.ConfigstoreMetaService/MetaDelete", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *configstoreMetaServiceClient) GetDefaultPartitionId(ctx context.Context, in *GetDefaultPartitionIdRequest, opts ...grpc.CallOption) (*GetDefaultPartitionIdResponse, error) {
	out := new(GetDefaultPartitionIdResponse)
	err := c.cc.Invoke(ctx, "/meta.ConfigstoreMetaService/GetDefaultPartitionId", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *configstoreMetaServiceClient) ApplyTransaction(ctx context.Context, in *MetaTransaction, opts ...grpc.CallOption) (*MetaTransactionResult, error) {
	out := new(MetaTransactionResult)
	err := c.cc.Invoke(ctx, "/meta.ConfigstoreMetaService/ApplyTransaction", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// ConfigstoreMetaServiceServer is the server API for ConfigstoreMetaService service.
type ConfigstoreMetaServiceServer interface {
	GetSchema(context.Context, *GetSchemaRequest) (*GetSchemaResponse, error)
	MetaList(context.Context, *MetaListEntitiesRequest) (*MetaListEntitiesResponse, error)
	MetaGet(context.Context, *MetaGetEntityRequest) (*MetaGetEntityResponse, error)
	MetaUpdate(context.Context, *MetaUpdateEntityRequest) (*MetaUpdateEntityResponse, error)
	MetaCreate(context.Context, *MetaCreateEntityRequest) (*MetaCreateEntityResponse, error)
	MetaDelete(context.Context, *MetaDeleteEntityRequest) (*MetaDeleteEntityResponse, error)
	GetDefaultPartitionId(context.Context, *GetDefaultPartitionIdRequest) (*GetDefaultPartitionIdResponse, error)
	ApplyTransaction(context.Context, *MetaTransaction) (*MetaTransactionResult, error)
}

// UnimplementedConfigstoreMetaServiceServer can be embedded to have forward compatible implementations.
type UnimplementedConfigstoreMetaServiceServer struct {
}

func (*UnimplementedConfigstoreMetaServiceServer) GetSchema(ctx context.Context, req *GetSchemaRequest) (*GetSchemaResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetSchema not implemented")
}
func (*UnimplementedConfigstoreMetaServiceServer) MetaList(ctx context.Context, req *MetaListEntitiesRequest) (*MetaListEntitiesResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method MetaList not implemented")
}
func (*UnimplementedConfigstoreMetaServiceServer) MetaGet(ctx context.Context, req *MetaGetEntityRequest) (*MetaGetEntityResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method MetaGet not implemented")
}
func (*UnimplementedConfigstoreMetaServiceServer) MetaUpdate(ctx context.Context, req *MetaUpdateEntityRequest) (*MetaUpdateEntityResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method MetaUpdate not implemented")
}
func (*UnimplementedConfigstoreMetaServiceServer) MetaCreate(ctx context.Context, req *MetaCreateEntityRequest) (*MetaCreateEntityResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method MetaCreate not implemented")
}
func (*UnimplementedConfigstoreMetaServiceServer) MetaDelete(ctx context.Context, req *MetaDeleteEntityRequest) (*MetaDeleteEntityResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method MetaDelete not implemented")
}
func (*UnimplementedConfigstoreMetaServiceServer) GetDefaultPartitionId(ctx context.Context, req *GetDefaultPartitionIdRequest) (*GetDefaultPartitionIdResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetDefaultPartitionId not implemented")
}
func (*UnimplementedConfigstoreMetaServiceServer) ApplyTransaction(ctx context.Context, req *MetaTransaction) (*MetaTransactionResult, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ApplyTransaction not implemented")
}

func RegisterConfigstoreMetaServiceServer(s *grpc.Server, srv ConfigstoreMetaServiceServer) {
	s.RegisterService(&_ConfigstoreMetaService_serviceDesc, srv)
}

func _ConfigstoreMetaService_GetSchema_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetSchemaRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ConfigstoreMetaServiceServer).GetSchema(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/meta.ConfigstoreMetaService/GetSchema",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ConfigstoreMetaServiceServer).GetSchema(ctx, req.(*GetSchemaRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ConfigstoreMetaService_MetaList_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(MetaListEntitiesRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ConfigstoreMetaServiceServer).MetaList(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/meta.ConfigstoreMetaService/MetaList",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ConfigstoreMetaServiceServer).MetaList(ctx, req.(*MetaListEntitiesRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ConfigstoreMetaService_MetaGet_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(MetaGetEntityRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ConfigstoreMetaServiceServer).MetaGet(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/meta.ConfigstoreMetaService/MetaGet",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ConfigstoreMetaServiceServer).MetaGet(ctx, req.(*MetaGetEntityRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ConfigstoreMetaService_MetaUpdate_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(MetaUpdateEntityRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ConfigstoreMetaServiceServer).MetaUpdate(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/meta.ConfigstoreMetaService/MetaUpdate",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ConfigstoreMetaServiceServer).MetaUpdate(ctx, req.(*MetaUpdateEntityRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ConfigstoreMetaService_MetaCreate_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(MetaCreateEntityRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ConfigstoreMetaServiceServer).MetaCreate(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/meta.ConfigstoreMetaService/MetaCreate",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ConfigstoreMetaServiceServer).MetaCreate(ctx, req.(*MetaCreateEntityRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ConfigstoreMetaService_MetaDelete_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(MetaDeleteEntityRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ConfigstoreMetaServiceServer).MetaDelete(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/meta.ConfigstoreMetaService/MetaDelete",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ConfigstoreMetaServiceServer).MetaDelete(ctx, req.(*MetaDeleteEntityRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ConfigstoreMetaService_GetDefaultPartitionId_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetDefaultPartitionIdRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ConfigstoreMetaServiceServer).GetDefaultPartitionId(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/meta.ConfigstoreMetaService/GetDefaultPartitionId",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ConfigstoreMetaServiceServer).GetDefaultPartitionId(ctx, req.(*GetDefaultPartitionIdRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ConfigstoreMetaService_ApplyTransaction_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(MetaTransaction)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ConfigstoreMetaServiceServer).ApplyTransaction(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/meta.ConfigstoreMetaService/ApplyTransaction",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ConfigstoreMetaServiceServer).ApplyTransaction(ctx, req.(*MetaTransaction))
	}
	return interceptor(ctx, in, info, handler)
}

var _ConfigstoreMetaService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "meta.ConfigstoreMetaService",
	HandlerType: (*ConfigstoreMetaServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetSchema",
			Handler:    _ConfigstoreMetaService_GetSchema_Handler,
		},
		{
			MethodName: "MetaList",
			Handler:    _ConfigstoreMetaService_MetaList_Handler,
		},
		{
			MethodName: "MetaGet",
			Handler:    _ConfigstoreMetaService_MetaGet_Handler,
		},
		{
			MethodName: "MetaUpdate",
			Handler:    _ConfigstoreMetaService_MetaUpdate_Handler,
		},
		{
			MethodName: "MetaCreate",
			Handler:    _ConfigstoreMetaService_MetaCreate_Handler,
		},
		{
			MethodName: "MetaDelete",
			Handler:    _ConfigstoreMetaService_MetaDelete_Handler,
		},
		{
			MethodName: "GetDefaultPartitionId",
			Handler:    _ConfigstoreMetaService_GetDefaultPartitionId_Handler,
		},
		{
			MethodName: "ApplyTransaction",
			Handler:    _ConfigstoreMetaService_ApplyTransaction_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "meta.proto",
}
